export interface Product {
  slug: string;
  name: string;
  image: string;
  variants: string[];
  units: string[];
  description: string;
}

export interface Category {
  slug: string;
  name: string;
  image: string;
  products: Product[];
}

export const categories: Category[] = [
  {
    slug: "steel",
    name: "Steel",
    image: "/materials/Cat-Steel.jpg",
    products: [
      {
        slug: "pipes",
        name: "Pipes",
        image: "/materials/Steel-pipes.jpg",
        variants: [
          "Anti-Siphonage Pipe",
          "Cast Iron Pipes",
          "Copper Pipes",
          "DI fitting",
          "DI pipe",
          "Drain Pipes or Waste Disposal Pipes",
          "Drainage Pipes",
          "Galvanized Iron Pipes",
          "GI flat",
          "GI pipe",
          "GI Rectangular tube",
          "GI square tube",
          "MS flat",
          "MS pipe",
          "MS Rectangular tube",
          "MS square tube",
          "Polythene Pipes",
          "PVC Pipes",
          "Rainwater Pipe",
          "Seamless pipe",
          "Soil Pipe",
          "Stoneware Pipes",
          "Vent Pipe",
        ],
        units: ["MT", "Mtrs"],
        description: "",
      },
      {
        slug: "structural-steel",
        name: "Structural Steel",
        image: "/materials/Structural-steel.jpg",
        variants: [
          "Angles",
          "Beams",
          "Billet",
          "Channels",
          "Coils",
          "Column",
          "Flats",
          "Hexagonal Bars",
          "Rectangular Bar",
          "Rounds Bar",
          "Sheet / Plates",
          "Square Bar",
          "Strips",
          "Wire Rods",
        ],
        units: ["KG", "MT"],
        description: "",
      },
      {
        slug: "tmt",
        name: "TMT",
        image: "/materials/TMT-Bars.jpg",
        variants: [
          "Binding Wire",
          "CRS",
          "Epoxy Coated",
          "TMT Bar",
          "TMT Coil",
          "Without Ribs",
        ],
        units: ["KG", "MT"],
        description: "",
      },
      {
  slug: "plates-coils",
  name: "Plates & Coils",
  image: "/materials/Plates-Coils.png",
  variants: [
    "MS Plates",
    "HR Plates",
    "HR Coils",
    "CR Sheets",
    "GI Sheets",
    "GP Coils",
    "Galvalume Coils",
    "Stainless Steel Plates",
    "Color Coated Coils",
    "Roofing Sheets",
    "Chequered Plates",
    "High Tensile Plates",
    "Wear Resistant Plates",
    "Boiler Quality Plates",
    "Pressure Vessel Plates",
    "Structural Steel Plates",
    "Alloy Steel Plates",
    "Electrical Steel Coils",
    "Shipbuilding Plates",
  ],
  units: ["KG", "MT"],
  description: "",
},
    ],
  },
  {
    slug: "cement",
    name: "Cement",
    image: "/materials/Cat-cement.jpg",
    products: [
      {
        slug: "bag",
        name: "Bag",
        image: "/materials/Cement-bag.jpg",
        variants: [
          "Coloured Cement",
          "Hydrophobic Portland Cement",
          "Ordinary Portland Cement 33 Grade",
          "Ordinary Portland Cement 43 Grade",
          "Ordinary Portland Cement 53 Grade",
          "Portland Pozzolana Cement (PPC)",
          "Portland Slag Cement (PSC)",
        ],
        units: ["MT", "No. of Bags"],
        description: "",
      },
      {
        slug: "block-jointing-mortar",
        name: "Block Jointing Mortar",
        image: "/materials/Block-Jointing-Mortar.jpg",
        variants: [
          "Type K Mortar Mix",
          "Type M Mortar Mix",
          "Type N Mortar Mix",
          "Type O Mortar Mix",
          "Type S Mortar Mix",
        ],
        units: ["Qtl"],
        description: "",
      },
      {
        slug: "bricks",
        name: "Bricks",
        image: "/materials/Bricks.jpg",
        variants: [
          "Burnt Clay Bricks",
          "Calcium Silicate Bricks",
          "Concrete Bricks",
          "Engineering Bricks",
          "Fly Ash Bricks",
          "Porotherm Smart Bricks Or Eco Bricks.",
          "Sun-Dried Bricks",
        ],
        units: ["Nos."],
        description: "",
      },
      {
        slug: "concrete-blocks",
        name: "Concrete Blocks",
        image: "/materials/Concrete-blocks.jpeg",
        variants: [
          "Bullnose Concrete Blocks",
          "Concrete Pillar Blocks",
          "Concrete Stretcher Blocks",
          "Expanded Clay Aggregate Solid Construction Blocks",
          "Hollow Concrete Blocks",
          "Jamb Concrete Blocks",
          "Lintel Blocks",
          "Partition Concrete Blocks",
          "Paving Blocks",
        ],
        units: ["CuM", "Nos."],
        description: "",
      },
      {
        slug: "concrete-ready-mix-concrete",
        name: "Concrete/ Ready Mix Concrete",
        image: "/materials/Concrete-_-Ready-Mix-Concrete-bag.jpg",
        variants: [
          "Air-Entrained Concrete",
          "High-Density Concrete",
          "Lightweight Concrete",
          "Normal Strength Concrete",
          "Plain or Ordinary Concrete",
          "Polymer Concrete",
          "Precast Concrete",
          "Prestressed Concrete",
          "Ready Mix Concrete",
          "Reinforced Concrete",
        ],
        units: ["CuM", "Nos."],
        description: "",
      },
      {
        slug: "fiber-reinforced-concrete",
        name: "Fiber Reinforced Concrete",
        image: "/materials/Fiber-Reinforced-Concrete.jpg",
        variants: [
          "Asbestos Fibers",
          "Carbon Fibers",
          "GFRC Glass Fiber Reinforced Concrete",
          "Organic Fibers",
          "Polypropylene Fiber Reinforced (PFR) cement mortar \u0026 concrete",
          "Steel Fiber Reinforced Concrete",
        ],
        units: ["KG", "M3"],
        description: "",
      },
      {
        slug: "ready-mix-plaster",
        name: "Ready Mix Plaster",
        image: "/materials/ready-mix-plaster-.jpg",
        variants: [
          "Cement Plaster",
          "Clay plaster",
          "Gypsum Plaster",
          "Heat-Resistant Plaster",
          "Lime Plaster",
          "POP",
        ],
        units: ["MT", "Nos."],
        description: "",
      },
    ],
  },
  {
    slug: "sand-aggregate-fly-ash",
    name: "Sand Aggregate Fly Ash",
    image: "/materials/Cat-Sand-Aggregate.jpg",
    products: [
      {
        slug: "fly-ash",
        name: "Fly Ash",
        image: "/materials/fly-ash.jpg",
        variants: ["Fly Ash"],
        units: ["MT"],
        description: "",
      },
      {
        slug: "sand",
        name: "Sand",
        image: "/materials/Sand.jpg",
        variants: [
          "Coarse Sand",
          "Concrete Sand",
          "Fill Sand",
          "Fine Sand",
          "M-Sand",
          "Pit Sand",
          "River Sand",
          "Utility Sand",
        ],
        units: ["Cu. Ft.", "CuM"],
        description: "",
      },
      {
        slug: "sand-aggregate",
        name: "Sand Aggregate",
        image: "/materials/send-aggregate.jpg",
        variants: ["Aggregate 10 mm", "Aggregate 20 mm", "Aggregate 40 mm"],
        units: ["CuM", "MT"],
        description: "",
      },
    ],
  },
  {
    slug: "chemical",
    name: "Chemical",
    image: "/materials/Cat-Chemicals.jpg",
    products: [
      {
        slug: "cleaning-chemicals",
        name: "Cleaning Chemicals",
        image: "/materials/cleaning-chemicals-1.jpg",
        variants: [
          "Acids",
          "Alkalies",
          "Bleaches",
          "Detergents",
          "Sanitizers",
          "Spirit Solvents",
        ],
        units: ["KG", "Ltr."],
        description: "",
      },
      {
        slug: "construction-chemicals",
        name: "Construction Chemicals",
        image: "/materials/Chemicals.jpg",
        variants: [
          "Adhesives",
          "Admixture High PC Based",
          "Admixture Low PC Based",
          "Admixture Mid PC Based",
          "Admixture Naptha Based",
          "Concrete Admixtures",
          "Concrete Curing Compound",
          "Epoxy Grouts",
          "Polymer Bonding Agents",
          "Protective and Decorative Agents",
          "Sealants and Caulks",
          "Water Repellents",
        ],
        units: ["KG", "Ltr."],
        description: "",
      },
      {
        slug: "micro-silica",
        name: "Micro Silica",
        image: "/materials/micro-silica.jpg",
        variants: [
          "Condensed Microsilica",
          "Powdered Microsilica",
          "Slurry Microsilica",
        ],
        units: ["KG", "MT"],
        description: "",
      },
      {
        slug: "waterproofing-chemicals",
        name: "Waterproofing Chemicals",
        image: "/materials/waterproofing-chemicals-.jpg",
        variants: [
          "Bituminous Membrane",
          "Cementitious Coating",
          "EPDM Rubber",
          "Polyurethane",
          "PVC Waterproofing Membrane",
          "Rubberized Asphalt",
          "Thermoplastic",
        ],
        units: ["KG", "Ltr."],
        description: "",
      },
    ],
  },
  {
    slug: "civil-and-infrastructure",
    name: "Civil and Infrastructure",
    image: "/materials/Cat-Civil-and-Infrastructure.jpg",
    products: [
      {
        slug: "flooring",
        name: "Flooring",
        image: "/materials/Flooring.jpg",
        variants: [
          "Bamboo",
          "Brick",
          "Concrete",
          "Granite",
          "Hardwood",
          "Laminate",
          "Linoleum",
          "Marble",
          "Red Oxide",
          "Terrazzo",
          "Vinyl",
          "Vitrified Tile",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "foundations",
        name: "Foundations",
        image: "/materials/Foundation.jpg",
        variants: [
          "Combined footing",
          "Deep Foundation",
          "Drilled Shafts or caissons",
          "Individual footing or isolated footing",
          "Pile foundation",
          "Raft or mat foundation",
          "Shallow foundation",
          "Strip foundation",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "gardening-landscaping",
        name: "Gardening \u0026 Landscaping",
        image: "/materials/Gardening-tools.jpg",
        variants: [
          "Cutting \u0026 Pruning Tools",
          "Garden Tool Set",
          "Garden Utilities",
          "Gardening Products",
          "Mowers \u0026 Trimmers",
          "Sprayers",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "hvac",
        name: "HVAC",
        image: "/materials/HVAC.jpg",
        variants: [
          "Duct free (Mini-split)",
          "Heating and cooling split systems",
          "Hybrid split system",
          "Packaged heating and air conditioning system",
        ],
        units: ["package", "Sq.Ft."],
        description: "",
      },
      {
        slug: "masonry",
        name: "Masonry",
        image: "/materials/masonry.jpg",
        variants: [
          "Bagged Concrete Masonry",
          "Block Masonry",
          "Brick Masonry",
          "Composite Masonry",
          "Gabion Masonry",
          "Reinforced Masonry",
          "Stone Masonry",
          "Veneer Masonry",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "pre-engineered-buildings",
        name: "Pre-Engineered Buildings",
        image: "/materials/Pre-engineereed-building.jpg",
        variants: [
          "Clear Span with Top running Crane",
          "Flat Roof",
          "Lean-to",
          "Mezzanine Floor",
          "Mono slope clear span",
          "Muti-Gable",
          "Roof System",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "roof",
        name: "Roof",
        image: "/materials/Roof.jpg",
        variants: [
          "Clipped Gable Roof",
          "Dutch Gable Roof",
          "Flat Roof (Low Slope Roof)",
          "Gable Roof",
          "Gambrel Roof",
          "Hip Roof",
          "Mansard Roof",
          "Shed Roof",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "scaffolding-formwork",
        name: "Scaffolding / Formwork",
        image: "/materials/Scaffolding.jpg",
        variants: [
          "Cantilever scaffolding",
          "Double scaffolding",
          "Kwikstage scaffolding",
          "Patented scaffolding",
          "Purlin",
          "shuttering ply",
          "Single scaffolding",
          "Steel scaffolding",
          "Suspended scaffolding",
          "Trestle scaffolding",
          "Tube and clip scaffolding",
          "Walkway Jali",
          "Wooden and bamboo scaffolding",
          "Wooden runner",
        ],
        units: ["KG", "Nos."],
        description: "",
      },
      {
        slug: "sheets",
        name: "Sheets",
        image: "/materials/Sheets.jpg",
        variants: ["GI sheets", "MS sheets", "Perforated"],
        units: ["KG", "Nos."],
        description: "",
      },
      {
        slug: "textiles",
        name: "Textiles",
        image: "/materials/Textile-1.jpg",
        variants: [
          "Architectural Membranes",
          "Awnings and canopies",
          "Hoardings / Signages",
          "Scaffolding Nets",
          "Tarpaulins",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "thermal-insulation",
        name: "Thermal Insulation",
        image: "/materials/Thermal-insulation.jpg",
        variants: [
          "Blanket: Batt and Roll Insulation",
          "Concrete Block Insulation",
          "Foam Board or Rigid Foam",
          "Insulating Concrete Forms",
          "Loose-Fill and Blown-In Insulation",
          "Radiant Barriers and Reflective Insulation Systems",
          "Rigid Fiber Board Insulation",
          "Sprayed-Foam and Foamed-In-Place Insulation",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "wall-cladding",
        name: "Wall Cladding",
        image: "/materials/wall-cladding-.jpg",
        variants: [
          "Aluminum cladding",
          "Brick cladding",
          "Ceramic cladding",
          "External foam cladding",
          "Fiber Cement Cladding",
          "Glass cladding",
          "Natural stone cladding",
          "Stainless Steel cladding",
          "Vinyl cladding",
          "Weatherboard cladding",
          "Wood cladding",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "waterproofing",
        name: "Waterproofing",
        image: "/materials/Waterproofing.jpg",
        variants: [
          "Bituminous Coating Waterproofing",
          "Bituminous Membrane Waterproofing",
          "Cementitious Waterproofing",
          "Liquid Waterproofing Membrane",
          "membrane waterproofing",
          "Polyurethane Liquid Membrane Waterproofing",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
    ],
  },
  {
    slug: "petroleum",
    name: "Petroleum",
    image: "/materials/Cat-Petroleum.jpg",
    products: [
      {
        slug: "bitumen",
        name: "Bitumen",
        image: "/materials/Bitumen.jpg",
        variants: [
          "Bitumen Emulsion",
          "Cut Back Bitumen",
          "Oxidized Bitumen Grades",
          "Penetration Grade Bitumen",
          "Polymer Modified Bitumen",
        ],
        units: ["KG", "Ltr."],
        description: "",
      },
      {
        slug: "coal",
        name: "Coal",
        image: "/materials/Coal.jpg",
        variants: ["Anthracite", "Bituminous", "Lignite", "Subbituminous"],
        units: ["MT", "Nos."],
        description: "",
      },
      {
        slug: "emulsion",
        name: "Emulsion",
        image: "/materials/Emulsion.jpg",
        variants: [
          "MIcroemulsions",
          "Multiple Emulsion",
          "Oil in Water Emulsion",
          "Water in Oil Emulsion",
        ],
        units: ["KG", "Ltr."],
        description: "",
      },
      {
        slug: "lubricant",
        name: "Lubricant",
        image: "/materials/lubricant-oil.jpg",
        variants: ["Dry Lubricants", "Penetrating Lubricants"],
        units: ["KG", "Ltr."],
        description: "",
      },
      {
        slug: "oil",
        name: "Oil",
        image: "/materials/Oil.jpg",
        variants: [
          "Engine oil",
          "Gear oil",
          "Grease",
          "Mineral Oils",
          "Natural Oils",
          "Synthetic Oils",
          "Transformer oil",
        ],
        units: ["MT", "Nos."],
        description: "",
      },
    ],
  },
  {
    slug: "interior-architecture",
    name: "Interior \u0026 Architecture",
    image: "/materials/Cat-Interior-Architecture.jpg",
    products: [
      {
        slug: "architecture",
        name: "Architecture",
        image: "/materials/Architecture.jpg",
        variants: [
          "Commercial Architect",
          "Conservation Architect",
          "Industrial Architect",
          "Interior Architect",
          "Landscape Architect",
          "Residential Architect",
          "Sustainable / Green Design Architect",
          "Urban Designer",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "door",
        name: "Door",
        image: "/materials/Door.jpg",
        variants: [
          "Aluminium Doors",
          "Battened \u0026 Ledged Doors",
          "Fiber Reinforced Plastic Doors",
          "Fiberglass Doors",
          "Flush Doors",
          "Framed \u0026 Paneled Doors",
          "Glass Doors",
          "PVC Doors",
          "Steel Doors",
          "Timber Wood",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "facades",
        name: "Facades",
        image: "/materials/facades.jpg",
        variants: [
          "Aluminum Composite facade",
          "Clay facade",
          "Curtain Walling facade",
          "Double-skin facade",
          "Glazing facade",
          "Homeostatic facade",
          "Insulated wall facade",
          "Panel frame facade",
          "Precast Concrete facade",
          "Self-cleaning facade",
          "Solar shading facade",
          "Steel and glass facade",
          "Steel facade",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "gates",
        name: "Gates",
        image: "/materials/Gates.jpg",
        variants: [
          "Automatic Gate",
          "Retractable Security Gate",
          "Sliding Gate",
          "Swing Gate",
          "Turnstile Gate",
          "Vertical Pivot Gate",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "glass",
        name: "Glass",
        image: "/materials/Glass.jpg",
        variants: [
          "Chromatic Glass",
          "Extra Clean Glass",
          "Float Glass",
          "Glass Blocks",
          "Glass Wool",
          "Insulated Glazed Units",
          "Laminated Glass",
          "Shatterproof Glass",
          "Tinted Glass",
          "Toughened Glass",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "hardware-and-bathroom-accessories",
        name: "Hardware and Bathroom Accessories",
        image: "/materials/hardware-and-washroom-accessories.jpg",
        variants: [
          "Bathroom Fixtures",
          "Cabinet Hardware",
          "Door Hardware",
          "Faucets",
          "Locks",
          "Paints and Coatings",
          "Sanitary Ware",
          "Showers",
          "Sinks",
        ],
        units: ["Nos.", "Piece"],
        description: "",
      },
      {
        slug: "interior",
        name: "Interior",
        image: "/materials/Interior.jpg",
        variants: [
          "Art Moderne Interior Design",
          "Contemporary Interior Design",
          "Eclectic Interior Design",
          "Farmhouse Interior Design",
          "Industrial Interior Design",
          "Mid-Century Interior Design",
          "Minimalist Interior Design",
          "Modern Interior Design",
          "Scandinavian Interior Design",
          "Shabby Chic Interior Design Style",
        ],
        units: ["Sq.Ft.", "Sqm"],
        description: "",
      },
      {
        slug: "plastics",
        name: "Plastics",
        image: "/materials/Plastics.jpg",
        variants: [
          "Acrylic",
          "Composites",
          "Polycarbonate",
          "Polypropylene",
          "Polyvinyl Chloride",
        ],
        units: ["KG", "Sq.Ft."],
        description: "",
      },
      {
        slug: "stone",
        name: "Stone",
        image: "/materials/Stone.jpg",
        variants: [
          "Basalt",
          "Gneiss",
          "Granite",
          "Laterite",
          "Limestone",
          "Marble",
          "Quartzite",
          "Sandstone",
          "Slate",
          "Travertine",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
      {
        slug: "window",
        name: "Window",
        image: "/materials/window.jpg",
        variants: [
          "Arched Windows",
          "Awning Windows",
          "Bay Windows",
          "Bow Windows",
          "Casement Windows",
          "Double Hung Windows",
          "Egress Windows",
          "Garden Windows",
          "Glass Block Windows",
          "Hopper Windows",
          "Jalousie Windows",
          "Other Window",
          "Picture Windows",
          "Round Circle Windows",
          "Single Hung Windows",
        ],
        units: ["Nos.", "Sq.Ft."],
        description: "",
      },
    ],
  },
  {
    slug: "solar",
    name: "Solar",
    image: "/materials/Cat-Solar.jpg",
    products: [
      {
        slug: "solar-cell",
        name: "Solar Cell",
        image: "/materials/solar-cell.jpeg",
        variants: [
          "Amorphous Silicon solar cell",
          "Biohybrid solar cell",
          "Cadmium telluride solar cell",
          "Concentrated PV cell",
          "Copper indium gallium selenide solar cells",
          "Crystalline silicon solar cell",
          "Dye-sensitized solar cell",
          "Float-zone silicon",
          "Gallium arsenide germanium solar cell",
          "Hybrid solar cell",
          "Luminescent solar concentrator",
          "Micromorph",
          "Monocrystalline solar cell",
          "Multi-junction solar cell",
          "Other Cell",
        ],
        units: ["Nos.", "W"],
        description: "",
      },
      {
        slug: "solar-module",
        name: "Solar Module",
        image: "/materials/solar-module.jpg",
        variants: [
          "Mono-crystalline Solar Modules",
          "Polycrystalline Solar Modules",
          "Thin-film Solar Modules",
        ],
        units: ["Qtl"],
        description: "",
      },
      {
        slug: "solar-panel",
        name: "Solar Panel",
        image: "/materials/solar-pannel.jpg",
        variants: [
          "ACDB \u0026 DCDB for solar plant",
          "Earthing material",
          "Lightning arrestor",
          "Monocrystalline solar panels",
          "Passivated Emitter and Rear Cell (PERC) panels",
          "Polycrystalline solar panels",
          "Solar modules Mono crystline",
          "Solar modules Polycrystline",
          "Solar On grid inverters",
          "Solar Structure made from GI",
          "Thin-film solar panels",
        ],
        units: ["Nos.", "W"],
        description: "",
      },
    ],
  },
  {
    slug: "electronic-and-electrical-accessories",
    name: "Electronic and Electrical Accessories",
    image: "/materials/Cat-Electrical-Accessories.jpg",
    products: [
      {
        slug: "appliances-and-utilities",
        name: "Appliances and Utilities",
        image: "/materials/Appliances-and-Utilities.jpg",
        variants: [
          "Air Conditioner",
          "Chimneys",
          "Fans",
          "Grinders \u0026 Juice Extractors",
          "Home Invertor \u0026 UPS",
          "Kitchen Appliances",
          "Refrigerators",
          "Room Heaters",
          "Washing Machines",
        ],
        units: ["Nos.", "Set"],
        description: "",
      },
      {
        slug: "cables-wire",
        name: "Cables \u0026 Wire",
        image: "/materials/Cables-_-Wire.jpg",
        variants: [
          "CCTV Cables",
          "Coaxial Cables",
          "Communication \u0026 Networking Cables",
          "High Tension Cables",
          "Industrial Wires \u0026 Cables",
          "Low Tension Cables",
          "Mounting \u0026 Cable Accessories",
          "Solar Cables",
          "Submersible Cables",
          "Telephone Cables",
        ],
        units: ["Mtr.", "Nos."],
        description: "",
      },
      {
        slug: "circuit-breakers-fuses",
        name: "Circuit Breakers \u0026 Fuses",
        image: "/materials/Circuit-Breakers-_-Fuses.jpg",
        variants: [
          "Air Circuit Breaker",
          "Fuses \u0026 Fuse Holders",
          "Isolators",
          "MCB",
          "MCCB",
          "Motor Circuit Breakers",
          "MPCB",
          "RCBO",
          "RCCB \u0026 ELCB",
          "RCD",
          "Surge Protection Devices",
          "Switchgears Accessories",
        ],
        units: ["Nos."],
        description: "",
      },
      {
        slug: "led-lighting",
        name: "LED \u0026 Lighting",
        image: "/materials/LED-_-Lighting.jpg",
        variants: [
          "Ceiling \u0026 Wall Lights",
          "Decorative Lights",
          "Lamp",
          "LED",
          "Light Blubs",
          "Lighting Accessories",
          "Outdoor Lighting",
          "Portable Lighting",
          "Smart Lights",
        ],
        units: ["Nos."],
        description: "",
      },
      {
        slug: "pump-and-motor",
        name: "Pump And Motor",
        image: "/materials/Pump-And-Motor.jpg",
        variants: [
          "Booster Pumps",
          "Centrifugal Pumps",
          "Control Motor Starters",
          "Gear Pump",
          "General Purpose Motor",
          "Sewage Pumps",
          "Shallow Well Pumps",
          "Submersible Pumps",
        ],
        units: ["Nos."],
        description: "",
      },
    ],
  },
  {
    slug: "miscellaneous",
    name: "Miscellaneous",
    image: "/materials/Cat-Others-Miscellaneous.jpg",
    products: [
      {
        slug: "automotive",
        name: "Automotive",
        image: "/materials/automotive.jpg",
        variants: [
          "Automoblie Rubber and Components",
          "Automotive Filters",
          "Automotive Tools",
          "Bikes Accessories",
          "Car Accessories",
          "Car Care and Cleaning",
          "Car Lighting",
          "Car Washers",
          "Clutch Part and Accessories",
          "Spare Parts",
        ],
        units: ["Nos.", "Set"],
        description: "",
      },
      {
        slug: "measurements-testings",
        name: "Measurements \u0026 Testings",
        image: "/materials/Measurenment-and-testing.jpg",
        variants: [
          "Air-Velocity Meters",
          "Detectors",
          "Electrical Power Testings",
          "Electronic and Bench Testing",
          "Flow Meters",
          "Indoor Air Quality Meters",
          "Laser Levels",
          "Measuring and Layout Tools",
          "Measuring Presicion Tools",
          "Milli \u0026 Micro OHM Meters",
          "Non- Electrical Properties Testings",
          "Process Monitoring Meters",
          "Temperature and Humidity Meters",
          "Weighing Scales",
        ],
        units: ["Nos.", "Set"],
        description: "",
      },
      {
        slug: "office-stationery-and-supplier",
        name: "Office Stationery and Supplier",
        image: "/materials/Office-stationery.jpg",
        variants: [
          "Cleaning and Housingkeeping",
          "IT \u0026 Electronics",
          "Office Furniture",
          "Security",
        ],
        units: ["Nos."],
        description: "",
      },
      {
        slug: "safety-and-ppe-supplies",
        name: "Safety and PPE Supplies",
        image: "/materials/Safety-and-ppe-supplies.jpg",
        variants: [
          "Fall Protection",
          "Fire Fighting Cloting and Accessories",
          "Hearing Protection",
          "Respiratory Masks",
          "Safety Gloves",
          "Safety Helmets",
          "Safety Jackets",
          "Safety Shoes",
          "Safety Sign and Signal",
          "Traffic Safety",
        ],
        units: ["Nos.", "Piece"],
        description: "",
      },
      {
        slug: "tool-and-machinery",
        name: "Tool and Machinery",
        image: "/materials/Tools-and-machinery.jpg",
        variants: [
          "Abrasives",
          "Cutting Tools and Machinery",
          "Fasteners",
          "Hand Tools",
          "Hydraulics",
          "Industrial Plant and Machinery",
          "Material Handling and Packaging",
          "Penumatics",
          "Power Tools",
          "Welding and Soldering",
        ],
        units: ["Nos.", "Set"],
        description: "",
      },
    ],
  },
];

export function getCategoryBySlug(slug: string): Category | undefined {
  return categories.find((category) => category.slug === slug);
}

export function getProductBySlug(
  catSlug: string,
  prodSlug: string,
): { category: Category; product: Product } | undefined {
  const category = getCategoryBySlug(catSlug);
  if (!category) return undefined;
  const product = category.products.find((item) => item.slug === prodSlug);
  if (!product) return undefined;
  return { category, product };
}
