/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferralRouteImport } from './routes/api/referral'
import { Route as ApiQuoteRequestsRouteImport } from './routes/api/quote-requests'
import { Route as ApiDemoBookingsRouteImport } from './routes/api/demo-bookings'
import { Route as ApiContactSalesRouteImport } from './routes/api/contact-sales'
import { Route as ApiContactRouteImport } from './routes/api/contact'

const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferralRoute = ApiReferralRouteImport.update({
  id: '/api/referral',
  path: '/api/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuoteRequestsRoute = ApiQuoteRequestsRouteImport.update({
  id: '/api/quote-requests',
  path: '/api/quote-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDemoBookingsRoute = ApiDemoBookingsRouteImport.update({
  id: '/api/demo-bookings',
  path: '/api/demo-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactSalesRoute = ApiContactSalesRouteImport.update({
  id: '/api/contact-sales',
  path: '/api/contact-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContactRoute = ApiContactRouteImport.update({
  id: '/api/contact',
  path: '/api/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-sales': typeof ApiContactSalesRoute
  '/api/demo-bookings': typeof ApiDemoBookingsRoute
  '/api/quote-requests': typeof ApiQuoteRequestsRoute
  '/api/referral': typeof ApiReferralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-sales': typeof ApiContactSalesRoute
  '/api/demo-bookings': typeof ApiDemoBookingsRoute
  '/api/quote-requests': typeof ApiQuoteRequestsRoute
  '/api/referral': typeof ApiReferralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/api/contact': typeof ApiContactRoute
  '/api/contact-sales': typeof ApiContactSalesRoute
  '/api/demo-bookings': typeof ApiDemoBookingsRoute
  '/api/quote-requests': typeof ApiQuoteRequestsRoute
  '/api/referral': typeof ApiReferralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/api/contact'
    | '/api/contact-sales'
    | '/api/demo-bookings'
    | '/api/quote-requests'
    | '/api/referral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/api/contact'
    | '/api/contact-sales'
    | '/api/demo-bookings'
    | '/api/quote-requests'
    | '/api/referral'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/api/contact'
    | '/api/contact-sales'
    | '/api/demo-bookings'
    | '/api/quote-requests'
    | '/api/referral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  ApiContactRoute: typeof ApiContactRoute
  ApiContactSalesRoute: typeof ApiContactSalesRoute
  ApiDemoBookingsRoute: typeof ApiDemoBookingsRoute
  ApiQuoteRequestsRoute: typeof ApiQuoteRequestsRoute
  ApiReferralRoute: typeof ApiReferralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/referral': {
      id: '/api/referral'
      path: '/api/referral'
      fullPath: '/api/referral'
      preLoaderRoute: typeof ApiReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/quote-requests': {
      id: '/api/quote-requests'
      path: '/api/quote-requests'
      fullPath: '/api/quote-requests'
      preLoaderRoute: typeof ApiQuoteRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/demo-bookings': {
      id: '/api/demo-bookings'
      path: '/api/demo-bookings'
      fullPath: '/api/demo-bookings'
      preLoaderRoute: typeof ApiDemoBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact-sales': {
      id: '/api/contact-sales'
      path: '/api/contact-sales'
      fullPath: '/api/contact-sales'
      preLoaderRoute: typeof ApiContactSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/contact': {
      id: '/api/contact'
      path: '/api/contact'
      fullPath: '/api/contact'
      preLoaderRoute: typeof ApiContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  ApiContactRoute: ApiContactRoute,
  ApiContactSalesRoute: ApiContactSalesRoute,
  ApiDemoBookingsRoute: ApiDemoBookingsRoute,
  ApiQuoteRequestsRoute: ApiQuoteRequestsRoute,
  ApiReferralRoute: ApiReferralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
